### ISSUE TITLE
Doesn't work locally?

### ISSUE THREAD

**Issue by petermorlion** [stackimpact/stackimpact-nodejs#5]
Is it possible this doesn't work when I run my application locally? I created an `index.js` file with the contents of [this post](https://stackimpact.com/blog/aws-lambda-cpu-and-memory-profiling-node-js/). I then created a serverless yaml file with this:

```
# For full config options, check the docs: docs.serverless.com

service: stackimpact-spike  

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 10 # Avoid cold start timeouts.
  region: ${opt:region}
  stage: ${opt:stage}

functions:
  main:
    handler: index.handler
    memorySize: 256
    events:
      - http: ANY {proxy+}

plugins:
  - serverless-offline
```

I've also done `npm install` for `serverless`, `stackimpact`, and `serverless-offline`.

Finally, I've entered the key as I can see in my StackImpact configuration tab.

When I run it with `./node_modules/serverless/bin/serverless offline`, I can make successfull requests, but nothing comes in my StackImpact dashboard (on any tab). All I see is a message "It may take a few minutes for the first time data to be available."

After my first request, I can see this in the console:
```
[13:48:47.684] StackImpact 1.3.10: Agent activated.
```

I've also run a  tool that made 2453 (successful) requests, and I've waited for quite some time now. I still don't see anything in the dashboard.

At the end, I see an error:
```
[13:57:03.613] StackImpact 1.3.10: Error uploading messages to the dashboard, backing off next upload
[13:57:03.614] StackImpact 1.3.10: connect ECONNREFUSED 127.0.0.1:443
[13:57:03.614] StackImpact 1.3.10: Error: connect ECONNREFUSED 127.0.0.1:443
```

I've seen #2 but that author mentions the wrong positioning of `stackimpact.start`. However, I've followed the blog post and put it outside my handler.

This all makes me think StackImpact doesn't work for locally running applications? Or am I doing something wrong?
